[project]
name = "fastapi-video"
version = "0.1.0"
description = "Teste para servir vídeo do fastapi para o front-end"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "jinja2>=3.1.5",
    "uvicorn>=0.34.0",
]
